apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: site-greeting
    namespace: teamsite-gitops
    literals:
      - GREETING_MESSAGE=Willkommen bei der Kodschul Team Site (GitOps-Demo)
